apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: learning.events
  labels:
    strimzi.io/cluster: learnflow-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 604800000
    segment.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dead-letter.queue
  labels:
    strimzi.io/cluster: learnflow-kafka
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 2592000000
    segment.ms: 604800000
